### ISSUE TITLE
Ingress reloads results in 404

### ISSUE THREAD

**Issue by hprotzek** [open-metadata/openmetadata-helm-charts#102]
After enabling the ingress config, browser reloads ends up in a 404. Navigating over the links still works.

Anything to pay attention here?

**Comment by dhruvinmaniar123** [comment]
Hi @hprotzek,

It seems the issue is not replicable on our local environments.

Here is what we tried to setup locally -
- Docker Desktop Kubernetes Cluster
- Install Nginx Controller
- Install OpenMetadata Helm Dependencies
- Install OpenMetadata Helm Charts with Ingress available (non https)

Opening the browser with nginx url and navigating around works for us. Even page reloads were working as expected.

Please let us know if there is something that is missing from your environment ?
Will await for your response on this issue. Thanks!

**Comment by akash-jain-10** [comment]
Closing this issue and marking it as stale!
