### ISSUE TITLE
k8s.gcr.io will be going away eventually

### ISSUE THREAD

**Issue by userbradley** [open-metadata/openmetadata-helm-charts#120]
It may be worth add to the `README` somewhere that due to the `k8s.gcr.io` registry being shut down soon, users may see errors with old helm chart

[See here for more details](https://kubernetes.io/blog/2023/03/10/image-registry-redirect/)

**Comment by akash-jain-10** [comment]
Hello @userbradley . Thanks for pointing this one! I've verified that the Images and the dependencies we are using are not coming from the source `k8s.gcr.io`. It seems our helm project remains unaffected due to this. I mark this thread as closed following the initial investigations!

Here is the detailed links of projects which are affected and have made the changes - https://github.com/kubernetes/k8s.io/issues/4780

Let us know if this helps!
