### ISSUE TITLE
Save TLS certificates in a Kubernetes secret 

### ISSUE THREAD

**Issue by revit13** [open-metadata/openmetadata-helm-charts#96]
It might be easier if there would be a possibility to save TLS certificates or openmetadata.keystore.jks in a Kubernetes secret which will be mounted to OM deployment container

Relates to https://github.com/open-metadata/OpenMetadata/issues/9022

**Comment by akash-jain-10** [comment]
Hello @revit13 . Since the keystore file is provided by user and is specific to end user, we might not be able to have a common implementation around this to include a kubernetes secret with Helm Chart. However, we already have extraVolumes and extraVolumeMounts that can attach the secrets as file created by end user. Closing this issue request. Thanks.
