### ISSUE TITLE
Add postStart to define commands to run after the pod is ready.

### ISSUE THREAD

**Issue by revit13** [open-metadata/openmetadata-helm-charts#98]
This can be used to automate processes such as initialization.
ref: https://github.com/hashicorp/vault-helm/blob/main/values.yaml#L494

**Comment by akash-jain-10** [comment]
Hello @revit13 . As per Kubernetes Documentation for [PostStart](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks).

> This hook is executed immediately after a container is created. However, there is no guarantee that the hook will execute before the container ENTRYPOINT. No parameters are passed to the handler.

Since it does not guarantee to execute the commands before container ENTRYPOINT, this might actually cause more issues in race condition scenarios which might get a little bit complicated for debug and troubleshoot.

Is there any specific scenario that requires this ability with OpenMetadata Helm Charts ? An alternative we use is running flyway db upgrade check with Helm PreUpgrade Hooks.

**Comment by revit13** [comment]
OK I see Thanks for the explanation. If you can provide instruction to **running flyway db upgrade check with Helm PreUpgrade Hooks** that would be great. Thanks
